-- Investigation database schema v1.0
-- Generated by OSINT Multi-Agent System
--
-- Normalized relational schema for investigation data export.
-- Designed for queryability with standard SQL tools (DB Browser, DBeaver, etc.)
-- without requiring any custom code.

CREATE TABLE IF NOT EXISTS investigation_metadata (
    investigation_id TEXT PRIMARY KEY,
    objective TEXT DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    metadata_json TEXT DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS facts (
    fact_id TEXT PRIMARY KEY,
    investigation_id TEXT NOT NULL,
    claim_text TEXT NOT NULL,
    assertion_type TEXT DEFAULT 'statement',
    claim_type TEXT DEFAULT 'event',
    content_hash TEXT,
    extraction_confidence REAL,
    claim_clarity REAL,
    temporal_value TEXT,
    temporal_precision TEXT,
    provenance_json TEXT DEFAULT '{}',
    entities_json TEXT DEFAULT '[]',
    stored_at TEXT,
    FOREIGN KEY (investigation_id) REFERENCES investigation_metadata(investigation_id)
);

CREATE TABLE IF NOT EXISTS classifications (
    fact_id TEXT PRIMARY KEY,
    investigation_id TEXT NOT NULL,
    impact_tier TEXT NOT NULL,
    dubious_flags_json TEXT DEFAULT '[]',
    priority_score REAL DEFAULT 0.0,
    credibility_score REAL DEFAULT 0.0,
    classification_reasoning_json TEXT DEFAULT '[]',
    classified_at TEXT,
    FOREIGN KEY (fact_id) REFERENCES facts(fact_id),
    FOREIGN KEY (investigation_id) REFERENCES investigation_metadata(investigation_id)
);

CREATE TABLE IF NOT EXISTS verification_results (
    fact_id TEXT PRIMARY KEY,
    investigation_id TEXT NOT NULL,
    verification_status TEXT NOT NULL,
    original_confidence REAL,
    confidence_boost REAL DEFAULT 0.0,
    final_confidence REAL,
    query_attempts INTEGER DEFAULT 0,
    queries_used_json TEXT DEFAULT '[]',
    supporting_evidence_json TEXT DEFAULT '[]',
    refuting_evidence_json TEXT DEFAULT '[]',
    origin_dubious_flags_json TEXT DEFAULT '[]',
    reasoning TEXT DEFAULT '',
    verified_at TEXT,
    requires_human_review INTEGER DEFAULT 0,
    human_review_completed INTEGER DEFAULT 0,
    FOREIGN KEY (fact_id) REFERENCES facts(fact_id),
    FOREIGN KEY (investigation_id) REFERENCES investigation_metadata(investigation_id)
);

CREATE TABLE IF NOT EXISTS sources (
    source_id TEXT PRIMARY KEY,
    source_domain TEXT,
    source_type TEXT,
    authority_score REAL,
    fact_count INTEGER DEFAULT 0,
    investigation_id TEXT,
    FOREIGN KEY (investigation_id) REFERENCES investigation_metadata(investigation_id)
);

CREATE TABLE IF NOT EXISTS entities (
    entity_id TEXT,
    investigation_id TEXT NOT NULL,
    name TEXT NOT NULL,
    canonical TEXT,
    entity_type TEXT,
    fact_ids_json TEXT DEFAULT '[]',
    PRIMARY KEY (entity_id, investigation_id),
    FOREIGN KEY (investigation_id) REFERENCES investigation_metadata(investigation_id)
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_facts_investigation ON facts(investigation_id);
CREATE INDEX IF NOT EXISTS idx_facts_hash ON facts(content_hash);
CREATE INDEX IF NOT EXISTS idx_classifications_tier ON classifications(impact_tier);
CREATE INDEX IF NOT EXISTS idx_classifications_score ON classifications(priority_score DESC);
CREATE INDEX IF NOT EXISTS idx_verification_status ON verification_results(verification_status);
CREATE INDEX IF NOT EXISTS idx_sources_investigation ON sources(investigation_id);
CREATE INDEX IF NOT EXISTS idx_entities_investigation ON entities(investigation_id);
