"""initial schema

Revision ID: c753fe39a0fb
Revises: 
Create Date: 2026-03-22 04:40:08.001838

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy.vector  # noqa: F401 -- Vector type used in column defs
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c753fe39a0fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('published_date', sa.String(length=64), nullable=True),
    sa.Column('source_name', sa.String(length=256), nullable=True),
    sa.Column('source_domain', sa.String(length=256), nullable=True),
    sa.Column('stored_at', sa.String(length=64), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('article_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('content_tsvector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', COALESCE(title, '') || ' ' || COALESCE(content, ''))", persisted=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_article_id'), 'articles', ['article_id'], unique=True)
    op.create_index('ix_articles_content_fts', 'articles', ['content_tsvector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_articles_investigation_id'), 'articles', ['investigation_id'], unique=False)
    op.create_table('classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fact_id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('credibility_score', sa.Float(), nullable=True),
    sa.Column('credibility_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dubious_flags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('classification_reasoning', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('impact_reasoning', sa.String(length=1024), nullable=True),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('classification_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investigation_id', 'fact_id', name='uq_classifications_inv_fact')
    )
    op.create_index(op.f('ix_classifications_fact_id'), 'classifications', ['fact_id'], unique=False)
    op.create_index(op.f('ix_classifications_investigation_id'), 'classifications', ['investigation_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('canonical', sa.Text(), nullable=True),
    sa.Column('entity_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_entity_id'), 'entities', ['entity_id'], unique=True)
    op.create_index(op.f('ix_entities_investigation_id'), 'entities', ['investigation_id'], unique=False)
    op.create_table('facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fact_id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('assertion_type', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('claim_clarity', sa.Float(), nullable=True),
    sa.Column('stored_at', sa.String(length=64), nullable=True),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quality_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('temporal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('numeric', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('relationships', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('variants', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('claim_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('claim_tsvector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', COALESCE(claim_text, ''))", persisted=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_facts_claim_fts', 'facts', ['claim_tsvector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_facts_content_hash'), 'facts', ['content_hash'], unique=False)
    op.create_index('ix_facts_embedding_hnsw', 'facts', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_facts_fact_id'), 'facts', ['fact_id'], unique=True)
    op.create_index(op.f('ix_facts_investigation_id'), 'facts', ['investigation_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=False),
    sa.Column('markdown_path', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synthesis_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investigation_id', 'version', name='uq_reports_inv_version')
    )
    op.create_index(op.f('ix_reports_content_hash'), 'reports', ['content_hash'], unique=False)
    op.create_index(op.f('ix_reports_investigation_id'), 'reports', ['investigation_id'], unique=False)
    op.create_table('verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fact_id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('original_confidence', sa.Float(), nullable=True),
    sa.Column('confidence_boost', sa.Float(), nullable=True),
    sa.Column('final_confidence', sa.Float(), nullable=True),
    sa.Column('search_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('supporting_evidence', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('refuting_evidence', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('queries_used', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('origin_dubious_flags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('reasoning', sa.String(length=2048), nullable=True),
    sa.Column('verification_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investigation_id', 'fact_id', name='uq_verifications_inv_fact')
    )
    op.create_index(op.f('ix_verifications_fact_id'), 'verifications', ['fact_id'], unique=False)
    op.create_index(op.f('ix_verifications_investigation_id'), 'verifications', ['investigation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verifications_investigation_id'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_fact_id'), table_name='verifications')
    op.drop_table('verifications')
    op.drop_index(op.f('ix_reports_investigation_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_content_hash'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_facts_investigation_id'), table_name='facts')
    op.drop_index(op.f('ix_facts_fact_id'), table_name='facts')
    op.drop_index('ix_facts_embedding_hnsw', table_name='facts', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_facts_content_hash'), table_name='facts')
    op.drop_index('ix_facts_claim_fts', table_name='facts', postgresql_using='gin')
    op.drop_table('facts')
    op.drop_index(op.f('ix_entities_investigation_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_classifications_investigation_id'), table_name='classifications')
    op.drop_index(op.f('ix_classifications_fact_id'), table_name='classifications')
    op.drop_table('classifications')
    op.drop_index(op.f('ix_articles_investigation_id'), table_name='articles')
    op.drop_index('ix_articles_content_fts', table_name='articles', postgresql_using='gin')
    op.drop_index(op.f('ix_articles_article_id'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
